name: Publish App to Production
run-name: Publish App to Production
on: workflow_dispatch
jobs:
  Supervisely-Publish:
    uses: supervisely-ecosystem/workflows/.github/workflows/common.yml@master
    with:
      SLUG: "${{ github.repository }}"
      RELEASE_VERSION: ""
      RELEASE_DESCRIPTION: ""
      RELEASE_TYPE: "publish"
      SUBAPP_PATHS: "__ROOT_APP__, subapp"
      MODELS_PATH: ""
      FRAMEWORK: ""
