name: Release branch
run-name: Release "${{ github.ref_name }}" branch
on:
  push:
    branches-ignore:
      - main
      - master
jobs:
  Supervisely-Release:
    uses: supervisely-ecosystem/workflows/.github/workflows/common.yml@master
    secrets:
      SUPERVISELY_DEV_API_TOKEN: "${{ env.SUPERVISELY_DEV_API_TOKEN }}"
      SUPERVISELY_PRIVATE_DEV_API_TOKEN: "${{ env.SUPERVISELY_PRIVATE_DEV_API_TOKEN }}"
      SUPERVISELY_PROD_API_TOKEN: "${{ env.SUPERVISELY_PROD_API_TOKEN }}"
      GH_ACCESS_TOKEN: "${{ env.GITHUB_TOKEN }}"
    with:
      SUPERVISELY_SERVER_ADDRESS: "${{ env.SUPERVISELY_DEV_SERVER_ADDRESS }}"
      SUPERVISELY_PROD_SERVER_ADDRESS: "${{ env.SUPERVISELY_PROD_SERVER_ADDRESS }}"
      SLUG: "${{ github.repository }}"
      RELEASE_VERSION: "${{ github.ref_name }}"
      RELEASE_DESCRIPTION: "'${{ github.ref_name }}' branch release"
      RELEASE_TYPE: "release-branch"
      SUBAPP_PATHS: "__ROOT_APP__, subapp"
