name: Release Models Manual
on:
  workflow_dispatch:
    inputs:
      models_path:
        type: string
        required: false
      det_models_path:
        type: string
        required: false
      framework:
        type: string
        required: true

jobs:
  release-models:
    uses: supervisely-ecosystem/workflows/.github/workflows/sync_models_common.yml@master
    with:
      MODELS_PATH: ${{ github.event.inputs.models_path }}
      DET_MODELS_PATH: ${{ github.event.inputs.models_path }}
      FRAMEWORK: ${{ github.event.inputs.framework }}
