name: Release Models Manual
on:
  workflow_dispatch:
    inputs:
      framework:
        description: "Framework of the models to release (e.g., YOLO)"
        type: string
        required: false
      models_path:
        description: "Path to the file models.json (e.g., supervisely_integration/models.json for YOLO)"
        type: string
        required: false
      # det_models_path:
      #   description: "[Legacy] Path to the file det_models_data.json (e.g., models/det_models_data.json for YOLOv8)"
      #   type: string
      #   required: false

jobs:
  release-models:
    uses: supervisely-ecosystem/workflows/.github/workflows/sync_models_common.yml@master
    with:
      MODELS_PATH: ${{ github.event.inputs.models_path }}
      DET_MODELS_PATH: ${{ github.event.inputs.models_path }}
      FRAMEWORK: ${{ github.event.inputs.framework }}
