name: Update Models
on:
  workflow_call:
    inputs:
      MODELS_PATH:
        type: string
        required: false
      DET_MODELS_PATH:
        type: string
        required: false
      SEG_MODELS_PATH:
        type: string
        required: false
      FRAMEWORK:
        type: string
        required: true
      SERVER_ADDRESS: # left here for backward compatibility, will be taken from config or env vars in release_models.py
        type: string
        required: false
    secrets: # left here for backward compatibility, will be taken from config or env vars in release_models.py
      API_TOKEN:
        required: false
jobs:
  Update-Models:
    runs-on: gha-runner-supervisely-ecosystem
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v6

      - name: Checkout workflows repository
        uses: actions/checkout@v6
        with:
          repository: supervisely-ecosystem/workflows
          ref: runner-updates
          path: workflow

      - name: Get Models Path and Framework
        id: get_inputs
        run: |
          . $HOME/.release_venv/bin/activate
          python workflow/get_inputs.py
        env:
          MODELS_PATH: ${{ inputs.MODELS_PATH }}
          FRAMEWORK: ${{ inputs.FRAMEWORK }}

      - name: Sync models
        run: |
          . $HOME/.release_venv/bin/activate
          python workflow/update_models.py
        env:
          DET_MODELS_PATH: ${{ inputs.DET_MODELS_PATH }}
          SEG_MODELS_PATH: ${{ github.event.inputs.models_path }}
